- hosts: all
  module_defaults:
    group/k8s:
      host: "{{host_api_server}}"
      validate_certs: no
  tasks:
    - name: Print the gateway for each host when defined
      ansible.builtin.debug:
        msg: Host api server {{host_api_server}}
    - name: Obtain access token
      k8s_auth:
        host: "{{host_api_server}}"
        validate_certs: no
        username: "{{username}}"
        password: "{{password}}"
      register: k8s_auth_results
    - name: Get Pod Information
      kubernetes.core.k8s_info:
        api_version: "{{ api_version }}"
        api_key: "{{ k8s_auth_results.k8s_auth.api_key }}"
        kind: Pod
        name: "{{ pod_name }}"
        namespace: "{{ pod_namespace }}"
      register: pod_info
    - name: Display pod info cpu limits
      debug:
        var: pod_info |  json_query('resources[].spec.containers[].resources')
    - name: Display pod info request limits
      debug:
        var: pod_info |  json_query('resources[].spec.containers[].resources')
    - name: Get Limit Information
      kubernetes.core.k8s_info:
        api_version: "{{ api_version }}"
        api_key: "{{ k8s_auth_results.k8s_auth.api_key }}"
        kind: LimitRange
        name: "{{ limit_name }}"
        namespace: "{{ namespace }}"
      register: limit_info
    - name: Display limit info
      debug:
        var: limit_info
