- hosts: all
  module_defaults:
    group/k8s:
      host: "{{host_api_server}}"
      validate_certs: no
  tasks:
   - name: Print the gateway for each host when defined
     ansible.builtin.debug:
       msg: Host api server {{host_api_server}}
   - name: Obtain access token
     kubernetes.core.k8s_auth:
       host: "{{host_api_server}}"
       validate_certs: no
       username: "{{username}}"
       password: "{{password}}"
     register: k8s_auth_results
   - name: Get the CronJob and latest job status
     kubernetes.core.k8s_info:
      host: "{{host_api_server}}"
      api_version: "{{ api_version }}"
      api_key: "{{ k8s_auth_results.k8s_auth.api_key }}"
      kind: CronJob
      name: "{{ name }}"
      namespace: "{{ namespace }}"
     register: cron_info
   - name: Display cron info
     debug:
      var: cron_info | json_query('resources[].status')
   - name: Get all jobs
     kubernetes.core.k8s_info:
      host: "{{host_api_server}}"
      api_version: "{{ api_version }}"
      api_key: "{{ k8s_auth_results.k8s_auth.api_key }}"
      kind: Job
      namespace: "{{ namespace }}"
     register: job_info
   - name: Display Job info
     debug:
      var: job_info
