
- name: Check Elasticsearch cluster status
  hosts: all
  become: true
  gather_facts: true
  vars:
    host: "{{ es_server }}"
    port: "{{ es_port }}"
    user: "{{ es_username }}"
    password: "{{ es_password }}"

  tasks:
    - name: Check Elasticsearch cluster status
      uri:
        url: "http://{{ host }}:{{ port }}/_cluster/health?pretty"
        user: "{{ user }}"
        password: "{{ password }}"
        method: GET
        return_content: true
      register: es_cluster_status

    - name: Print Elasticsearch cluster status
      debug:
        msg: "{{ es_cluster_status.content | from_json }}"
