
- name: Check Elasticsearch Node CPU and JVM heap usage information
  hosts: all
  become: true
  gather_facts: true
  vars:
    host: "{{ es_server }}"
    port: "{{ es_port }}"
    user: "{{ es_username }}"
    password: "{{ es_password }}"

  tasks:
    - name: Check Elasticsearch Node CPU and JVM heap usage information
      uri:
        url: "http://{{ host }}:{{ port }}/_nodes/stats/process,jvm"
        user: "{{ user }}"
        password: "{{ password }}"
        method: GET
        return_content: true
      register: es_node_stats

    - name: Print Elasticsearch Node CPU and JVM heap usage information
      debug:
        msg: "{{ es_node_stats.content | from_json }}"
