
- name: Check Elasticsearch Node health status
  hosts: all
  become: true
  gather_facts: true
  vars:
    host: "{{ es_server }}"
    port: "{{ es_port }}"
    user: "{{ es_username }}"
    password: "{{ es_password }}"

  tasks:
    - name: Check Elasticsearch Node health status
      uri:
        url: "http://{{ host }}:{{ port }}/_cluster/health?pretty"
        user: "{{ user }}"
        password: "{{ password }}"
        method: GET
        return_content: true
        status_code: 200
      register: es_health_status

    - name: Print Elasticsearch Node health status
      debug:
        var: es_health_status.content
