
- name: Check Elasticsearch Capacity Limit
  hosts: all
  become: true
  gather_facts: true
  vars:
    host: "{{ es_server }}"
    port: "{{ es_port }}"
    user: "{{ es_username }}"
    password: "{{ es_password }}"

  tasks:

    - name: Print Elasticsearch Capacity Limit
      uri:
        url: "http://{{ host }}:{{ port }}/_cat/allocation?v"
        user: "{{ user }}"
        password: "{{ password }}"
        method: GET
        return_content: yes
      register: es_capacity_limit

    - name: Print Elasticsearch Capacity Limit
      debug:
        msg: "{{ es_capacity_limit.content }}"
